### ISSUE TITLE
Not working with `cakePHP 2.5.5

### ISSUE THREAD

**Issue by papakay** [vdeep/TimthumbPlugin#8]
Please is there a way to get this to work with cakePHP 5.5

**Comment by vdeep** [comment]
I just checked this with CakePHP 2.6.7 and it seems to be working fine. Can you tell me if you are getting any error? And also please check if you have given proper permissions to the tmp/timthumb folder, which is the default folder where this plugin writes the temporary files.

**Comment by papakay** [comment]
Thanks Vdeep, the problem was actually a permission issue and it's working fine now.  Thanks once again.
